/* include/autoconf.h.  Generated by configure.  */
/* sys/autoconf/autoconf.hin.  Generated from sys/autoconf/configure.ac by autoheader.  */

/* Exceptions to autopickup (experimental) */
#undef AUTOPICKUP_EXCEPTIONS

/* Blackmarket */
#undef BLACKMARKET
#define BLACKMARKET 

/* A BSD like system */
#undef BSD

/* Charon's boat, enables Cerebus (not implemented) */
#undef CHARON

/* Allow smaller screens */
#undef CLIPPING
#define CLIPPING 

/* Unix on win32 */
#undef CYGWIN32

/* The default windowing system */
#undef DEFAULT_WINDOW_SYS
#define DEFAULT_WINDOW_SYS "tty"

/* Support transparent tilesets */
#undef DISPLAY_LAYERS
#define DISPLAY_LAYERS 

/* Data librarian */
#undef DLB
#define DLB 

/* Dungeon growth */
#undef DUNGEON_GROWTH
#define DUNGEON_GROWTH 

/* Dwarf race */
#undef DWARF
#define DWARF 

/* Remember which monsters have been eaten */
#undef EATEN_MEMORY
#define EATEN_MEMORY 

/* Engraving the E-word repels monsters */
#undef ELBERETH
#define ELBERETH 

/* Show experience on bottom line */
#undef EXP_ON_BOTL
#define EXP_ON_BOTL 

/* Guns and Bullets */
#undef FIREARMS
#define FIREARMS 

/* OpenGL graphics */
#undef GL_GRAPHICS

/* GNU regex is available */
#undef GNU_REGEX
#define GNU_REGEX 

/* Gold is kept on object chains (experimental) */
#undef GOLDOBJ

/* Define to 1 if you have the declaration of `strncmpi', and to 0 if you
   don't. */
#undef HAVE_DECL_STRNCMPI
#define HAVE_DECL_STRNCMPI 0

/* Define to 1 if you have the declaration of `strnicmp', and to 0 if you
   don't. */
#undef HAVE_DECL_STRNICMP
#define HAVE_DECL_STRNICMP 0

/* Define to 1 if you have the <inttypes.h> header file. */
#undef HAVE_INTTYPES_H
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `SDL' library (-lSDL). */
#undef HAVE_LIBSDL

/* Define to 1 if you have the <memory.h> header file. */
#undef HAVE_MEMORY_H
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#undef HAVE_STDINT_H
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#undef HAVE_STDLIB_H
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#undef HAVE_STRINGS_H
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#undef HAVE_STRING_H
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#undef HAVE_SYS_STAT_H
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#undef HAVE_SYS_TYPES_H
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#undef HAVE_UNISTD_H
#define HAVE_UNISTD_H 1

/* Invisible objects */
#undef INVISIBLE_OBJECTS
#define INVISIBLE_OBJECTS 

/* Keep save files after restore */
#undef KEEP_SAVE

/* Keystone Kops */
#undef KOPS
#define KOPS 

/* Dimsabers */
#undef LIGHTSABERS
#define LIGHTSABERS 

/* Spells are light sources */
#undef LIGHT_SRC_SPELL
#define LIGHT_SRC_SPELL 

/* GNU Linux */
#undef LINUX
#define LINUX 

/* TTY graphics menu color */
#undef MENU_COLOR
#define MENU_COLOR 

/* Microsoft Window's native graphics */
#undef MSWIN_GRAPHICS

/* Prevent wishing for special artifacts */
#undef NOARTIFACTWISH

/* No void type available */
#undef NOVOID

/* Disable loading and saving bones levels */
#undef NO_BONES

/* Shopkeeper services */
#undef OTHER_SERVICES
#define OTHER_SERVICES 

/* Define to the address where bug reports for this package should be sent. */
#undef PACKAGE_BUGREPORT
#define PACKAGE_BUGREPORT "http://sourceforge.net/bugs/?group_id=9746"

/* Define to the full name of this package. */
#undef PACKAGE_NAME
#define PACKAGE_NAME "SLASHEM"

/* Define to the full name and version of this package. */
#undef PACKAGE_STRING
#define PACKAGE_STRING "SLASHEM 0.0.8"

/* Define to the one symbol short name of this package. */
#undef PACKAGE_TARNAME
#define PACKAGE_TARNAME "slashem"

/* Define to the version of this package. */
#undef PACKAGE_VERSION
#define PACKAGE_VERSION "0.0.8"

/* Posix regex is available */
#undef POSIX_REGEX

/* proxy graphics */
#undef PROXY_GRAPHICS

/* Spoon */
#undef P_SPOON
#define P_SPOON 

/* Redo last command */
#undef REDO
#define REDO 

/* Special Rogue-like levels */
#undef REINCARNATION

/* Show score on bottom line */
#undef SCORE_ON_BOTL

/* Software SDL graphics */
#undef SDL_GRAPHICS

/* Succubi/incubi seduction */
#undef SEDUCE
#define SEDUCE 

/* Display damage reports */
#undef SHOW_DMG
#define SHOW_DMG 

/* Display object weight */
#undef SHOW_WEIGHT
#define SHOW_WEIGHT 

/* Kitchen sinks */
#undef SINKS
#define SINKS 

/* Define to 1 if you have the ANSI C header files. */
#undef STDC_HEADERS
#define STDC_HEADERS 1

/* Ability to ride monsters */
#undef STEED
#define STEED 

/* Use strncmpi */
#undef STRNCMPI

/* A System V like system */
#undef SYSV
#define SYSV 

/* Tourist class */
#undef TOURIST
#define TOURIST 

/* Console output */
#undef TTY_GRAPHICS
#define TTY_GRAPHICS 

/* Object unpolymorphing */
#undef UNPOLYPILE
#define UNPOLYPILE 

/* Allow user-defined regex mapping from messages to sounds (Qt with NAS only)
   */
#undef USER_SOUNDS

/* Use regular expressions */
#undef USE_REGEX_MATCH
#define USE_REGEX_MATCH 

/* Perseus' Wallet */
#undef WALLET_O_P
#define WALLET_O_P 

/* Fancy mazes */
#undef WALLIFIED_MAZE
#define WALLIFIED_MAZE 

/* An MS-Windows system */
#undef WIN32

/* The person allowed to use the -D option */
#undef WIZARD
#define WIZARD "wizard"

/* X11 graphics */
#undef X11_GRAPHICS

/* Yeoman class */
#undef YEOMAN
#define YEOMAN 

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#undef YYTEXT_POINTER

/* Zoutherner class */
#undef ZOUTHERN
